name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Droplet app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DROPLETHOSTSECRET}} # IP address of the server you wish to ssh into
          key: ${{secrets.DROPLETKEYSECRET}} # Private or public key of the server
          username: ${{ secrets.DROPLETUSERNAMESECRET }} # User of the server you want to ssh into
     
          script: |
            mkdir test 
            cd test 
            git clone git@github.com:SamHobbsOrg/BlazorWasmDigitalOcean.git 
            echo 'Deployment successful to digital ocean'
